webapp/src/GymPlus/src/Entity/Notif.php
<?php

namespace App\Entity;

use App\Repository\NotifRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: NotifRepository::class)]
class Notif
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(name: "idProduit", nullable: true)]
    private ?int $idProduit = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $etat = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $etatCommentaire = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $titre = null;

    #[ORM\Column(name: "nomUser" , length: 255, nullable: true)]
    private ?string $nomUser = null;

    #[ORM\Column]
    private ?\DateTime $datevente;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdProduit(): ?int
    {
        return $this->idProduit;
    }

    public function setIdProduit(?int $idProduit): static
    {
        $this->idProduit = $idProduit;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(?string $etat): static
    {
        $this->etat = $etat;

        return $this;
    }

    public function getEtatCommentaire(): ?string
    {
        return $this->etatCommentaire;
    }

    public function setEtatCommentaire(?string $etatCommentaire): static
    {
        $this->etatCommentaire = $etatCommentaire;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(?string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getNomUser(): ?string
    {
        return $this->nomUser;
    }

    public function setNomUser(?string $nomUser): static
    {
        $this->nomUser = $nomUser;

        return $this;
    }

    public function getDatevente(): ?\DateTime
    {
        return $this->datevente;
    }

    public function setDatevente(\DateTime $datevente): static
    {
        $this->datevente = $datevente;

        return $this;
    }

   
}

webapp/src/GymPlus/src/Controller/EquipmentController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\EquipementsDetailsRepository;
use App\Form\EquipementType;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Persistence\ManagerRegistry;
use App\Repository\MaintenancesRepository;
use App\Form\MaintenanceType;
use App\Form\ModifyMaintenanceType;
use Symfony\Component\Validator\Constraints\Json;
use Symfony\Component\HttpFoundation\JsonResponse;
use App\Repository\UserRepository;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\Mime\Part\DataPart;
use Symfony\Component\Mime\Part\File;
use Knp\Snappy\Pdf;
use Knp\Bundle\SnappyBundle\Snappy\Response\PdfResponse;

class EquipmentController extends AbstractController
{
    #[Route('/dashboard/equipments', name: 'app_equipments')]
    public function manageEquipements(EquipementsDetailsRepository $repo, Request $req, ManagerRegistry $reg): Response
    {
        
        $form = $this->createForm(EquipementType::class);
        $form->handleRequest($req);
        if ($form->isSubmitted() && $form->isValid()) {
            $equipement = $form->getData();
            $entityManager = $reg->getManager();
            $entityManager->persist($equipement);
            $entityManager->flush();
        }

        $equipements = $repo->getEquipementsDetails();

        return $this->render('dashboard/equipment/equipements.html.twig', [
            'controller_name' => 'EquipmentController',
            'equipments' => $equipements,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/dashboard/equipments/edit/{id}', name: 'app_equipments_edit')]
    public function manageEquipementsDetails(EquipementsDetailsRepository $repo, Request $req, ManagerRegistry $reg, $id, MailerInterface $mailer, UserRepository $repo1): Response
    {
        $equipement = $repo->find($id);
        $form = $this->createForm(EquipementType::class, $equipement);
        if ($equipement->getEtat() == 'Under Maintenance')
            $form->remove('etat');
        $form->handleRequest($req);
        if ($form->isSubmitted() && $form->isValid()) {
            if ($equipement->getEtat() == 'Bad'){
                
                try{
                    $admins = $repo1->getAdminList();
                    $emails = [];
                    foreach ($admins as $admin) 
                        $emails[] = $admin->getEmail();
                    $emails = implode(',', $emails);
                    $html = file_get_contents('dashboard/htmlassets/index.html');
                    $html = str_replace("{E1}", $id, $html);
                    
                    $email = (new Email())
                        ->from('gymplus-noreply@grandelation.com')
                        ->to($emails)
                        ->subject('Maintenance Request')
                        ->embed(fopen('dashboard/htmlassets/assets/image-5.png', 'r'), 'image-5', 'image/png')
                        ->html($html);
                    $mailer->send($email);
                }catch(\Exception $e){
                    $this->addFlash('error', 'Error sending email');
                }
            
                //$this->addFlash('success', 'Email sent successfully');
            }
                    
            $entityManager = $reg->getManager();
            $entityManager->persist($equipement);
            $entityManager->flush();
            return $this->redirectToRoute('app_equipments');
        }

        return $this->render('dashboard/equipment/edit_equipements.html.twig', [
            'controller_name' => 'EquipmentController',
            'form' => $form->createView(),
        ]);
    }

    #[Route('/dashboard/equipments/delete/{id}', name: 'app_equipments_delete')]
    public function deleteEquipements(EquipementsDetailsRepository $repo, $id): Response
    {
        $equipement = $repo->find($id);

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($equipement);
        $entityManager->flush();

        return $this->redirectToRoute('app_equipments');
    }

    #[Route('/dashboard/maintenances/', name: 'app_maintenances')]
    public function manageMaintenances(MaintenancesRepository $repo, Request $req, ManagerRegistry $reg, MailerInterface $mailer, UserRepository $repo1): Response
    {
        $form = $this->createForm(MaintenanceType::class);
        $form->handleRequest($req);
        if ($form->isSubmitted() && $form->isValid()) {
            $maintenance = $form->getData();
            $equipment = $maintenance->getEquipementsDetails();
            $equipment->setEtat('Under Maintenance');
            try{
                $admins = $repo1->getAdminList();
                $emails = [];
                foreach ($admins as $admin) 
                    $emails[] = $admin->getEmail();
                $emails = implode(',', $emails);
                $html = file_get_contents('dashboard/htmlassets/index.html');
                $html = str_replace("{E1}", $equipment->getId(), $html);
                
                $email = (new Email())
                    ->from('gymplus-noreply@grandelation.com')
                    ->to($emails)
                    ->subject('Maintenance Request')
                    ->embed(fopen('dashboard/htmlassets/assets/image-5.png', 'r'), 'image-5', 'image/png')
                    ->html($html);
                $mailer->send($email);
            }catch(\Exception $e){
                $this->addFlash('error', 'Error sending email');
            }
            // $this->addFlash('success', 'Email sent successfully');
            $entityManager = $reg->getManager();
            $entityManager->persist($maintenance);
            $entityManager->flush();
        }
        $maintenances = $repo->getMaintenances();

        return $this->render('dashboard/equipment/maintenances.html.twig', [
            'controller_name' => 'EquipmentController',
            'maintenances' => $maintenances,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/dashboard/maintenances/edit/{id}', name: 'app_maintenances_edit')]
    public function manageMaintenancesDetails(MaintenancesRepository $repo, Request $req, ManagerRegistry $reg, $id): Response
    {
        $maintenance = $repo->find($id);
        $form = $this->createForm(ModifyMaintenanceType::class, $maintenance);
        $form->handleRequest($req);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $reg->getManager();
            $entityManager->persist($maintenance);
            $entityManager->flush();
            return $this->redirectToRoute('app_maintenances');
        }

        return $this->render('dashboard/equipment/edit_maintenances.html.twig', [
            'controller_name' => 'EquipmentController',
            'form' => $form->createView(),
        ]);
    }

    #[Route('/dashboard/maintenances/delete/{id}', name: 'app_maintenances_delete')]
    public function deleteMaintenances(MaintenancesRepository $repo, $id): Response
    {
        $maintenance = $repo->find($id);
        $entityManager = $this->getDoctrine()->getManager();
        $equipment = $maintenance->getEquipementsDetails();
        $equipment->setEtat('Good');
        $entityManager->remove($maintenance);
        $entityManager->flush();

        return $this->redirectToRoute('app_maintenances');
    }

    #[Route('/equipments', name: 'app_memequipments')]
    public function index(EquipementsDetailsRepository $repo): Response
    {
        return $this->render('main/equipments/equipments.html.twig', [
            'controller_name' => 'EquipmentController',
            'equipments' => $repo->getEquipementsDetails(),
        ]);
    }

    #[Route('/api/sendmailmaint/{id}', name: 'app_sendmail')]
    public function sendMail($id, UserRepository $repo1, MailerInterface $mailer): Response
    {
        //bundle: Symfony/Mailer
        try{
            $admins = $repo1->getAdminList();
            $emails = [];
            foreach ($admins as $admin) 
                $emails[] = $admin->getEmail();
            $emails = implode(',', $emails);
            $html = file_get_contents('dashboard/htmlassets/index.html');
            $html = str_replace("{E1}", $id, $html);
            
            $email = (new Email())
                ->from('gymplus-noreply@grandelation.com')
                ->to($emails)
                ->subject('Maintenance Request')
                ->embed(fopen('dashboard/htmlassets/assets/image-5.png', 'r'), 'image-5', 'image/png')
                ->html($html);

            $mailer->send($email);
        }catch(\Exception $e){
            return new JsonResponse(['status' => 'error']);
        }
        return new JsonResponse(['status' => 'success']);
    }

    #[Route('/api/generatePDFmaint/{idm}', name: 'app_generatePDF')]
    public function generatePDF($idm, MaintenancesRepository $repo, Pdf $pdf): Response
    {
        $maintenance = $repo->find($idm);
        $html = file_get_contents('dashboard/htmlassets/attestation.html');
        $html = str_replace("{E1}", $maintenance->getEquipementsDetails()->getId(), $html);
        $days = date_diff($maintenance->getDateMaintenance(), new \DateTime())->format('%a');
        $html = str_replace("{E2}", $days, $html);
        $price = 200*$days;
        $html = str_replace("{E3}", $price, $html);
        $curdate = new \DateTime();
        $html = str_replace("{E4}", $curdate->format('Y-m-d'), $html);
        $html = str_replace("{E5}", $maintenance->getId(), $html);
        $pdf->setOption('enable-local-file-access', true);
        $html = str_replace("assets/",realpath('dashboard/htmlassets/assets/')."/", $html);

        return new PdfResponse(
            $pdf->getOutputFromHtml($html),
            'files.pdf'

webapp/src/GymPlus/templates/dashboard/equipment/edit_equipements.html.twig
{% extends "dashboard/base.html.twig" %}

{% block content %}
<div class="content-body default-height" style="min-height: 878px;">
    <div class="container-fluid">
        <div class="page-titles">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Dashboard</a></li>
                <li class="breadcrumb-item active"><a href="javascript:void(0)">Equipments</a></li>
            </ol>
        </div>
        <!-- row -->
        {% if form.etat is not defined %}
            <div class="alert alert-warning solid alert-right-icon alert-dismissible fade show">
					<span><i class="mdi mdi-alert"></i></span>
						<button type="button" class="close h-100" data-dismiss="alert" aria-label="Close"><span><i class="mdi mdi-close"></i></span>
					</button>
					<strong>Warning!</strong> This equipment is under maintenance, you can't change its state.
				</div>
        {% endif %}

        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Edit Equipement</h4>
                    </div>
                    <div class="card-body">
                    {{ form_start(form, { 'attr' :{'class': 'centered-form', 'novalidate': 'novalidate'}}) }}
                        <div class="form-row">
                            <div class="form-group col-md-4">
                                {{ form_label(form.name) }}
                                {{ form_widget(form.name, {'attr' : {'class' : 'form-control'}}) }}
                                <small class="text-danger">{{ form_errors(form.name) }}</small>
                            </div>
                            <div class="form-group col-md-4">
                                {{ form_label(form.description) }}
                                {{ form_widget(form.description, {'attr' : {'class' : 'form-control'}}) }}
                                <small class="text-danger">{{ form_errors(form.description) }}</small>
                            </div>
                            <div class="form-group col-md-4">
                                {{ form_label(form.dureeDeVie) }}
                                {{ form_widget(form.dureeDeVie, {'attr' : {'class' : 'form-control'}}) }}
                                <small class="text-danger">{{ form_errors(form.dureeDeVie) }}</small>
                            </div>
                        </div>
                        {% if form.etat is defined %}
                            <div class="form-row">
                                <div class="form-group col-md-4">
                                
                                        {{ form_label(form.etat) }}
                                            {{ form_widget(form.etat, {'attr' : {'class' : 'form-control'}}) }}
                                        
                                    <small class="text-danger">{{ form_errors(form.etat) }}</small>
                                </div>
                            </div>
                        {% endif %}
                        {{ form_widget(form.submit) }}
                    {{ form_end(form) }}
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

webapp/src/GymPlus/templates/dashboard/equipment/edit_maintenances.html.twig
{% extends "dashboard/base.html.twig" %}

{% block content %}
<div class="content-body default-height" style="min-height: 878px;">
    <div class="container-fluid">
        <div class="page-titles">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Dashboard</a></li>
                <li class="breadcrumb-item active"><a href="javascript:void(0)">Equipments</a></li>
            </ol>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Edit Maintenance</h4>
                    </div>
                    <div class="card-body">
                    {{ form_start(form, {'attr': { 'class': 'centered-form', 'novalidate':'novalidate'}}) }}
                        <div class="form-row">
                            
                        
                            <div class="form-group col-md-4">
                                {{ form_label(form.dateMaintenance) }}
                                {{ form_widget(form.dateMaintenance, {'attr' : {'class' : 'form-control'}}) }}
                                <small class="text-danger">{{ form_errors(form.dateMaintenance) }}</small>
                            </div>
                            <div class="form-group col-md-4">
                                {{ form_label(form.status) }}
                                {{ form_widget(form.status, {'attr' : {'class' : 'form-control'}}) }}
                                <small class="text-danger">{{ form_errors(form.status) }}</small>
                            </div>
                            
                        </div>
                       
                        {{ form_widget(form.submit) }}
                    {{ form_end(form) }}
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

webapp/src/GymPlus/templates/dashboard/equipment/equipements.html.twig
{% extends 'dashboard/base.html.twig' %}

{% block css %}
	<!-- Datatable -->
	<link href="{{asset('dashboard/vendor/datatables/css/jquery.dataTables.min.css')}}" rel="stylesheet">
	{{ parent() }}
{% endblock %}

{% block content %}
        <div class="content-body">
            <div class="container-fluid">
                <div class="page-titles">
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="javascript:void(0)">Dashboard</a></li>
						<li class="breadcrumb-item active"><a href="javascript:void(0)">Equipments</a></li>
					</ol>
                </div>
                <!-- row -->
				<div class="alert alert-warning solid alert-right-icon alert-dismissible fade show">
					<span><i class="mdi mdi-alert"></i></span>
						<button type="button" class="close h-100" data-dismiss="alert" aria-label="Close"><span><i class="mdi mdi-close"></i></span>
					</button>
					<strong>Warning!</strong> As a staff/admin, you can modify the state of the equipments. Be careful as this will cost the company money.
				</div>

				<div class="row">
					<div class="col-lg-12">
						<div class="card">
							<div class="card-header">
								<h4 class="card-title">Add Equipement</h4>
							</div>
							<div class="card-body">
							{{ form_start(form, { 'attr':{ 'class': 'centered-form', 'novalidate': 'novalidate'}}) }}
								<div class="form-row">
									<div class="form-group col-md-4">
										{{ form_label(form.name) }}
										{{ form_widget(form.name, {'attr' : {'class' : 'form-control'}}) }}
										<small class="text-danger">{{ form_errors(form.name) }}</small>
									</div>
									<div class="form-group col-md-4">
										{{ form_label(form.description) }}
										{{ form_widget(form.description, {'attr' : {'class' : 'form-control'}}) }}
										<small class="text-danger">{{ form_errors(form.description) }}</small>
									</div>
									<div class="form-group col-md-4">
										{{ form_label(form.dureeDeVie) }}
										{{ form_widget(form.dureeDeVie, {'attr' : {'class' : 'form-control'}}) }}
										<small class="text-danger">{{ form_errors(form.dureeDeVie) }}</small>
									</div>
								</div>
								<div class="form-row">
									<div class="form-group col-md-4">
										{{ form_label(form.etat) }}
										{{ form_widget(form.etat, {'attr' : {'class' : 'form-control'}}) }}
										<small class="text-danger">{{ form_errors(form.etat) }}</small>
									</div>
								</div>
								{{ form_widget(form.submit) }}
							{{ form_end(form) }}
							</div>
							
						</div>
					</div>
				</div>


                <div class="row">
					<div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Equipments</h4>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table id="example5" class="display min-w850">
                                        <thead>
                                            <tr>
												<th>Id</th>
                                                <th>Name</th>
												<th>Description</th>
												<th>Lifetime</th>
												<th>State</th>
												<th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
											{% for e in equipments %}

                                            <tr>
											
												<td>{{ e.id }}</td>
												<td>{{ e.name }}</td>
												<td>{{ e.description }}</td>
												<td>{{ e.dureedevie }}</td>
												

												<td>
													{% if e.etat|upper == 'GOOD' %}
													<span class="badge light badge-success">
													<i class="fa fa-circle text-success mr-1"></i>
													{% elseif e.etat|upper == 'BAD' %}
													<span class="badge light badge-warning">
													<i class="fa fa-circle text-warning mr-1"></i>
													
													{% else %}
													<span class="badge light badge-danger">
													<i class="fa fa-circle text-danger mr-1"></i>
													{% endif %}
														{{ e.etat | capitalize}}
													</span>
												</td>
												<td>
													<div class="dropdown ms-auto text-end c-pointer">
														<div class="btn-link" data-toggle="dropdown">
															<svg width="24px" height="24px" viewBox="0 0 24 24" version="1.1"><g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"><rect x="0" y="0" width="24" height="24"></rect><circle fill="#000000" cx="5" cy="12" r="2"></circle><circle fill="#000000" cx="12" cy="12" r="2"></circle><circle fill="#000000" cx="19" cy="12" r="2"></circle></g></svg>
														</div>
														<div class="dropdown-menu dropdown-menu-right">
															<a class="dropdown-item" onmouseover="this.classList.add('bg-warning'); this.classList.add('text-white')" onmouseout="this.classList.remove('bg-warning');  this.classList.remove('text-white')" href="{{ path('app_equipments_edit', {'id': e.id}) }}"><i class="fa fa-pencil me-2"></i> Modify Equipement</a>
															<a class="dropdown-item" onmouseover="this.classList.add('bg-danger'); this.classList.add('text-white')" onmouseout="this.classList.remove('bg-danger');  this.classList.remove('text-white')" href="{{ path('app_equipments_delete', {'id': e.id}) }}"><i class="fa fa-trash me-2"></i> Delete Equipement</a>
														</div>
													</div>
												</td>										
                                            </tr>
											{% endfor %}
                                            
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
				</div>
                    
			</div>
        </div>
        <!--**********************************
            Content body end
        ***********************************-->
{% endblock %}

{% block js %}
	{{ parent() }}
	<!-- Datatable -->
	<script src="{{asset('dashboard/vendor/datatables/js/jquery.dataTables.min.js')}}"></script>
	<script src="{{asset('dashboard/js/plugins-init/datatables.init.js')}}"></script>
{% endblock %}

webapp/src/GymPlus/templates/dashboard/equipment/maintenances.html.twig
{% extends 'dashboard/base.html.twig' %}

{% block css %}
	<!-- Datatable -->
	<link href="{{asset('dashboard/vendor/datatables/css/jquery.dataTables.min.css')}}" rel="stylesheet">
	{{ parent() }}
{% endblock %}

{% block content %}
        <div class="content-body">
            <div class="container-fluid">
                <div class="page-titles">
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="javascript:void(0)">Dashboard</a></li>
						<li class="breadcrumb-item active"><a href="javascript:void(0)">Equipments</a></li>
					</ol>
                </div>
                <!-- row -->
				<div class="alert alert-warning solid alert-right-icon alert-dismissible fade show">
					<span><i class="mdi mdi-alert"></i></span>
						<button type="button" class="close h-100" data-dismiss="alert" aria-label="Close"><span><i class="mdi mdi-close"></i></span>
					</button>
					<strong>Warning!</strong> As a staff/admin, you can modify the state of the equipments. Be careful as this will cost the company money.
				</div>

				<div class="row">
					<div class="col-lg-12">
						<div class="card">
							<div class="card-header">
								<h4 class="card-title">Add Maintenance</h4>
							</div>
							<div class="card-body">
							{{ form_start(form,{ 'attr' : { 'class': 'centered-form', 'novalidate':'novalidate'}}) }}
								<div class="form-row">
									<div class="form-group col-md-4">
										{{ form_label(form.dateMaintenance) }}
										{{ form_widget(form.dateMaintenance, {'attr' : {'class' : 'form-control'}}) }}
										<small class="text-danger">{{ form_errors(form.dateMaintenance) }}</small>
									</div>
									<div class="form-group col-md-4">
										{{ form_label(form.status) }}
										{{ form_widget(form.status, {'attr' : {'class' : 'form-control'}}) }}
										<small class="text-danger">{{ form_errors(form.status) }}</small>
									</div>
									<div class="form-group col-md-4">
										{{ form_label(form.equipementsDetails) }}
										{{ form_widget(form.equipementsDetails, {'attr' : {'class' : 'form-control'}}) }}
										<small class="text-danger">{{ form_errors(form.equipementsDetails) }}</small>
									</div>
								</div>
								
								{{ form_widget(form.submit) }}
							{{ form_end(form) }}
							</div>
							
						</div>
					</div>
				</div>

                <div class="row">
					<div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Equipments</h4>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table id="example5" class="display min-w850">
                                        <thead>
                                            <tr>
												<th>Id</th>
												<th>Equipement Id</th>
												<th>Date Maintenance</th>
												<th>Status</th>
												<th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
											{% for e in maintenances %}

                                            <tr>
												<td>{{ e.id }}</td>
												<td>{{ e.equipementsDetails.id }}</td>
												<td>{{ e.dateMaintenance|date }}</td>
												

												<td>
													
													<span class="badge light badge-danger">
													<i class="fa fa-circle text-danger mr-1"></i>
														{{ e.status | capitalize}}
													</span>
												</td>
												<td>
													<div class="dropdown ms-auto text-end c-pointer">
														<div class="btn-link" data-toggle="dropdown">
															<svg width="24px" height="24px" viewBox="0 0 24 24" version="1.1"><g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"><rect x="0" y="0" width="24" height="24"></rect><circle fill="#000000" cx="5" cy="12" r="2"></circle><circle fill="#000000" cx="12" cy="12" r="2"></circle><circle fill="#000000" cx="19" cy="12" r="2"></circle></g></svg>
														</div>
														<div class="dropdown-menu dropdown-menu-right">
															<a class="dropdown-item" onmouseover="this.classList.add('bg-warning'); this.classList.add('text-white')" onmouseout="this.classList.remove('bg-warning');  this.classList.remove('text-white')" href="{{ path('app_maintenances_edit', {'id': e.id}) }}"><i class="fa fa-pencil me-2"></i> Modify Maintenance</a>
															<a class="dropdown-item" onmouseover="this.classList.add('bg-danger'); this.classList.add('text-white')" onmouseout="this.classList.remove('bg-danger');  this.classList.remove('text-white')" href="{{ path('app_maintenances_delete', {'id': e.id}) }}"><i class="fa fa-trash me-2"></i> Delete Maintenance</a>
															<a class="dropdown-item" onmouseover="this.classList.add('bg-success'); this.classList.add('text-white')" onmouseout="this.classList.remove('bg-success');  this.classList.remove('text-white')" href="{{ path('app_generatePDF', {'idm': e.id}) }}"><i class="fa fa-eye me-2"></i> Generate PDF</a>
														</div>
													</div>
												</td>										
                                            </tr>
											{% endfor %}
                                            
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
				</div>
                    
			</div>
        </div>
        <!--**********************************
            Content body end
        ***********************************-->
{% endblock %}

{% block js %}
	{{ parent() }}
	<!-- Datatable -->
	<script src="{{asset('dashboard/vendor/datatables/js/jquery.dataTables.min.js')}}"></script>
	<script src="{{asset('dashboard/js/plugins-init/datatables.init.js')}}"></script>
{% endblock %}